// <auto-generated />
namespace ShopTechOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update234 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update234));
        
        string IMigrationMetadata.Id
        {
            get { return "202408261402581_update234"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
